services:
  feedback:
    image: feedback:${VERSION}
    container_name: feedback
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NACOSDSN=${NACOSDSN}
    networks:
      - feedback-network


networks:
  feedback-network:
    driver: bridge