# 飞书 app
client:
  appID: "xxxxx"
  appSecret: "xxxxx"

# JWT 配置
jwt:
  secretKey: "xxxxx"  # JWT 加密秘钥
  encKey: "xxxxx"  # JWT 加密敏感信息秘钥
  timeout: 2592000          # 一个月过期一次

# 中间件配置
middleware:
  allowedOrigins:
    - "*"  # 允许跨域访问的来源地址，例如前端开发服务器地址

# 基础表格信息，改表格用于储存其他表格的各种基础信息
baseTable:
  tableToken: "xxxxx"
  tableId: "xxxxx"
  viewId: "xxxxx"

# 发送通知的内容
content:
  type: "template"                              # 发送卡片时候的默认值
  data:
    template_id: "xxxxx"                # 卡片模版id
    #template_version_name: "1.0.0"             # 卡片模版版本，若不填，则为最新版本 这里不填，如果要填，则修改配置文件中的结构体，添加一个字段
    template_variable:                          # 卡片模版中设置的变量
      feedback_content: "反馈内容"
      feedback_source: "反馈来源"
      feedback_type: "反馈类型"

# 发送通知人员的open_id
open_ids:
  - name: "xxx"
    open_id: "xxxxx"

# 要发送的群组
chat_ids:
  - name: "xxxxx"
    chat_id: "xxxxx"

redis:
  addr: "xxxxx:6379"
  password: "xxxxx"
  db: 0

mysql:
  addr: "xxxxx:3306"
  dbname: "xxxxx"
  username: "xxxxx"
  password: "xxxxx"

log:
  file: "logs/app.log"  # 日志文件路径
  maxSize: 5  # 单个日志文件的最大大小，单位为 MB
  maxBackups: 10  # 保留的旧日志文件数量
  maxAge: 30  # 日志文件的最大保存天数
  compress: false  # 是否压缩旧日志文件

# 请求限流配置(令牌桶算法)
limiter:
  capacity: 1000  # 令牌桶容量
  fillInterval: 1 # 每秒补充令牌的次数
  quantum: 100 # 每次放置的令牌数

basicAuth:
  - username: "xxxxx"
    password: "xxxxx"